config/routes.rb
Rails.application.routes.draw do
  resources :cities
  root :to => 'static_pages#home'
  get '/search' => 'static_pages#search', :as => 'search_page'
  get '/about' => 'static_pages#about'
  get '/faq' => 'static_pages#faq'
  get '/covid' => 'static_pages#covid'
  get '/air' => 'static_pages#air'
  get '/meteo' => 'static_pages#meteo'
  get '/securite' => 'static_pages#security'
  get '/restauration' => 'static_pages#restauration'
  get '/fun' => 'static_pages#fun'
  post 'cities/:id' => 'cities#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

 mount_uploader :image, ImageUploader

  def self.search(search)
     where("name LIKE ?", "%#{search}%")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    #@cities = City.all.sort(:score)
      @cities = City.all.sort_by { |city| - city[:score] }
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
   end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :region, :place, :air, :security, :food, :weather, :moving, :covid, :score, :fun, :image, :classement)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @cities = City.all.sort_by { |city| - city[:score] }


  end

  def search
    @cities = City.all
      if params[:search]
          @cities = City.search(params[:search]).order("created_at DESC")
      else
       @cities = City.all.order('created_at DESC')
      end
  end

  def about
  end

  def faq
  end

  def covid
    @cities = City.all.sort_by { |city| - city[:covid] }
  end

  def air
    @cities = City.all.sort_by { |city| - city[:air] }
  end

  def restauration
    @cities = City.all.sort_by { |city| - city[:food] }
  end

  def security
    @cities = City.all.sort_by { |city| - city[:security] }
  end

  def meteo
    @cities = City.all.sort_by { |city| - city[:weather] }
  end

  def fun
    @cities = City.all.sort_by { |city| - city[:fun] }

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @city.region %>
</p>

<p>
  <strong>Place:</strong>
  <%= @city.place %>
</p>

<p>
  <strong>Air:</strong>
  <%= @city.air %>
</p>

<p>
  <strong>Security:</strong>
  <%= @city.security %>
</p>

<p>
  <strong>Food:</strong>
  <%= @city.food %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @city.weather %>
</p>

<p>
  <strong>Moving:</strong>
  <%= @city.moving %>
</p>
<p>
  <strong>Covid:</strong>
  <%= @city.covid %>
</p>
<p>
  <strong>Score:</strong>
  <%= @city.score %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/_footer.html.erb
<!-- footer -->
    <div class="footer">
        <div class="container">
            <hr class="footer-line">
            <div class="row ">
                <!-- footer-about -->
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                    <div class="footer-widget ">
                        <div class="footer-title">Entreprise</div>
                        <ul class="list-unstyled">
                            <li><%= link_to "A propos", about_path %></li>
                            <li> <%= link_to "FAQ", faq_path %></li>
                            <!--<li><a href="#">Support</a></li>
                            <li><a href="#">Press</a></li>-->
                            <li><a href="#">Legal & Privacy</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.footer-about -->
                <!-- footer-links -->
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                    <div class="footer-widget ">
                        <div class="footer-title">Quick Links</div>
                        <ul class="list-unstyled">
                            <li><a href="#">News</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.footer-links -->
                <!-- footer-links
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                    <div class="footer-widget ">
                        <div class="footer-title">Social</div>
                        <ul class="list-unstyled">
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Google +</a></li>
                            <li><a href="#">Linked In</a></li>
                            <li><a href="#">Facebook</a></li>
                        </ul>
                    </div>
                </div>-->
                <!-- /.footer-links -->
                <!-- footer-links -->
                <div class="col-xl-4 col-lg-4 col-md-12 col-sm-6 col-6 ">
                    <div class="footer-widget ">
                        <h3 class="footer-title">Inscrivez-vous à la Newsletter</h3>
                        <form>
                            <div class="newsletter-form">
                                <input class="form-control" placeholder="Enter Your Email address" type="text">
                                <button class="btn btn-default btn-sm" type="submit">Go</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.footer-links -->
                <!-- tiny-footer -->
            </div>
            <div class="row ">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center ">
                    <div class="tiny-footer">
                        <p>Copyright © All Rights Reserved 2020 | Template Design & Development by <a href="https://easetemplate.com/downloads/bitcoin-cryptocurrency-website-template-amazing-design " target="_blank" class="copyrightlink">EaseTemplate</a></p>
                    </div>
                </div>
                <!-- /. tiny-footer -->
            </div>
        </div>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Voyageurs De france", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "A propos", about_path, class:"navbar-brand" %>
        <%= link_to "FAQ", faq_path, class:"navbar-brand" %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= form_tag(search_page_path, method: "get", class: "search-discover js-form-search-location search-discover--hero", role: "form") do %>
             <div class="search-discover__inner">
               <%= text_field_tag :search, params[:search], class:"search-discover__input-location js-location", placeholder: "Rechercher une ville" %>
               <button type="submit" class="btn btn-danger btn-lg" data-ga-category="Home" data-ga-action="Search">
                 <i class="fa fa-search visible-xs"></i>
                 <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                  <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                  </svg>
               </button>

             </div>
            <% end %>
    </ul>
  </div>
</nav>

app/views/static_pages/about.html.erb
 <div class="row">
  <div class="text-center">
    <h1 class="title">Manifesto</h1>
  </div>
  <h3 class="about">Je m'appelle Jean-rodriguez Kinouani et
     j'ai fondé Voyageurs De France.  <br> <br> Notre mission est simple : Aider les gens à trouver des lieux
   de vacances qui les correspondent vraiment, pour aimer encore plus voyager en France.
  </h3>
  <div class="text-center">
    <h1 class="title">Pourquoi</h1>
  </div>
  <div class="text-center">
    <h1 class="title">Comment</h1>
  </div>
  <div class="text-center">
    <h1 class="title">Quoi</h1>
  </div>
 </div>

app/views/static_pages/air.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la moins polluée</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/covid.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus sure concernant le Covid</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/faq.html.erb
<div class="row">
 <div class="text-center">
   <h1 class="title">Foire aux questions</h1>
 </div>
</div>

app/views/static_pages/food.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus sure concernant le Covid</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/fun.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus fun</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i + city.fun.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="dimmer">
 <div class="banner text-center">
   <div class="text-center">
     <h1 class="proposition">Explorez la Fance</h1>
     <h2 class="baseline">Choisissez vos lieux de vacances selon vos critères</h2>
   </div>
 </div>
 </div>
</div>
<div class="container">
<div class="row">
  <div class="col-md-2">
    <h2>Filtres</h2>
    <ul>
      <li>
          <%= link_to "covid", covid_path %>
      </li>
      <li>
          <%= link_to "Air", air_path %>
      </li>
      <li>
          <%= link_to "Sécurité", securite_path %>
      </li>
      <li>
          <%= link_to "Restauration", restauration_path %>
      </li>
      <li>
          <%= link_to "Météo", meteo_path %>
      </li>
      <li>
          <%= link_to "Fun", fun_path %>
      </li>
    </ul>

  </div>
  <div class="col-md-10">
    <div class="text-center">
      <h2>Villes</h2>
    </div>
    <div class="row">
      <%= hidden_field_tag i = 0 %>

                <!-- Team member -->
                <% @cities.each do |city| %>

                  <%= i = i + 1 %>

                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
                        <div class="mainflip">
                            <div class="frontside">
                                <div class="card"><%= image_tag(city.image, class:"img-responsive") %>


                                    <div class="card-body text-center">
                                        <h4 class="card-title"><%= city.name %></h4>
                                        <p class="card-text">Region : <%= city.region %></p>
                                    </div>
                                </div>
                            </div>
                            <div class="backside">
                                <div class="card">
                                    <div class="card-body text-center mt-4">
                                      <h5 class="book_title">Restauration : <%= city.food %></h5>
                                      <h5 class="book_title">Qualité de l'air : <%= city.air %></h5>
                                      <h5 class="book_title">Météo : <%= city.weather %></h5>
                                      <h5 class="book_title">Transport : <%= city.moving %></h5>
                                      <h5 class="book_title">Covid : <%= city.covid %></h5>
                                      <h5 class="book_title">Fun : <%= city.fun %></h5>
                                      <h5 class="book_title">Sécurité :   <%= city.security %><%= puts i %></h5>
                                      <h5 class="book_title">classement : <%= city.classement.to_i %></h5>

                                        <p class="card-text">
                                          This is basic card with image on top, title, descriptio title, description</p>
                                          <%= button_to "Voir plus", city ,:method => :post, class:"btn btn-primary btn-sm"   %>
                                          <%=  i.to_i %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
    </div>


    <!--<div class="row">
          <% @cities.each do |city| %>
           <div class="col-lg-3  col-md-3 col-xs-12" id="row_book">
            <div class="text-center">
              <%= link_to (image_tag(city.image, class:"card-img-top")), root_path %>
              <h5 class="book_title"><%= city.name %></h5>
              <h5 class="book_title">Region : <%= city.region %></h5>
              <h5 class="book_title">Endroit : <%= city.place %></h5>
              <h5 class="book_title">Restauration : <%= city.food %></h5>
              <h5 class="book_title">Qualité de l'air : <%= city.air %></h5>
              <h5 class="book_title">Météo : <%= city.weather %></h5>
              <h5 class="book_title">Transport : <%= city.moving %></h5>
              <h5 class="book_title">Covid : <%= city.covid %></h5>
              <h5 class="book_title">Fun : <%= city.fun %></h5>
              <h5 class="book_title">Sécurité :   <%= city.security %></h5>
              <h5 class="book_title">Score : <%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i + city.fun.to_i %></h5>
              <h5><%= link_to 'Voir', city %></h5>
            </div>
        </div>
        <% end %>
    </div>-->
</div>
</div>
</div>

app/views/static_pages/meteo.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus ensoleilée</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/restauration.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus gastronomique</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/static_pages/search.html.erb
<div class="container">
    <div class="row">
      <div class="text-center">
        <h3 class="title_reunion">
          <% if @cities.blank? %>
            <h3 class="no_city">Désolé il n'y pas de livre ou d'auteur avec ce mot "<%= params[:search] %>"</br> </h3>
            <i class="fa fa-book" aria-hidden="true" ></i>

            <% else %>
              <h3 class="title_reunion">Voici le résultat pour <%= params[:search] %></h3>

          <% end %>
            <h1>Cities</h1>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Region</th>
                  <th>Place</th>
                  <th>Air</th>
                  <th>Security</th>
                  <th>Food</th>
                  <th>Weather</th>
                  <th>Moving</th>
                  <th>Covid</th>
                  <th>Score</th>
                </tr>
              </thead>

              <tbody>

                <% @cities.each do |city| %>
                  <tr>
                    <td><%= city.name %></td>
                    <td><%= city.region %></td>
                    <td><%= city.place %></td>
                    <td><%= city.air %></td>
                    <td><%= city.security %></td>
                    <td><%= city.food %></td>
                    <td><%= city.weather %></td>
                    <td><%= city.moving %></td>
                    <td><%= city.covid %></td>
                    <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i + city.fun.to_i%></td>

                    <!--<td><%= link_to 'Show', city %></td>
                    <td><%= link_to 'Edit', edit_city_path(city) %></td>
                    <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
    </div>
  </div>

app/views/static_pages/security.html.erb
<p id="notice"><%= notice %></p>

<h1>La ville la plus sure </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th>Place</th>
      <th>Air</th>
      <th>Security</th>
      <th>Food</th>
      <th>Weather</th>
      <th>Moving</th>
      <th>Covid</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>

    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region %></td>
        <td><%= city.place %></td>
        <td><%= city.air %></td>
        <td><%= city.security %></td>
        <td><%= city.food %></td>
        <td><%= city.weather %></td>
        <td><%= city.moving %></td>
        <td><%= city.covid %></td>
        <td><%= city.score = city.covid.to_i + city.food.to_i + city.air.to_i + city.security.to_i + city.weather.to_i + city.moving.to_i %></td>

        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>